import type { Page } from '@app/types';

export enum LocalKeys {
  PLAYER_PAUSED = 'PLAYER_PAUSED',
  PLAYER_VOLUME = 'PLAYER_VOLUME',
  CURRENT_PLAYING_TRACK = 'CURRENT_PLAYING_TRACK',
  CURRENT_PLAYING_TRACK_ID = 'CURRENT_PLAYING_TRACK_ID',
  CURRENT_PLAYING_TRACK_TIME = 'CURRENT_PLAYING_TRACK_TIME',
  CURRENT_PLAYING_TRACK_DURATION = 'CURRENT_PLAYING_TRACK_DURATION',
  CURRENT_QUEUE_IDS = 'CURRENT_QUEUE_IDS',
  CURRENT_PLAYLIST_ID = 'CURRENT_PLAYLIST_ID',
  CURRENT_PLAYLIST_TRACKS = 'CURRENT_PLAYLIST_TRACKS',
  SHUFFLE_ON = 'SHUFFLE_ON',
  REPEAT_MODE = 'REPEAT_MODE'
}
